os: linux
language: python
python:
  - "3.6"

env:
  - MELPA_PR_URL=https://github.com/melpa/melpa/pull/6819
install:
  - pip install .
  - pip install mypy
  - pytest --doctest-modules
  - mypy --ignore-missing-imports .

script:
  - EXPECT_ERROR=2 make
